package com.company.vansales.app.utils.enums

enum class BatchScanTypesEnum {
    CASH_MATERIALS,
    STOCK_COUNT,
    CREDIT_MATERIAL,
    BILL_TO_BILL,
    OFF_LOAD,
    FILL_UP,
    EXCHANGE_MATERIALS,
    FREE_MATERIALS,
    CANCEL_CASH,
    CANCEL_CREDIT,
    COLLECTION,
    LOAD_REQUEST,
    EOD_REPORT,
    SALES_SUMMARY,
    VISITS_SUMMARY,
    COLLECTION_SUMMARY,
    STOCK_SUMMARY,
    LOAD_TRANSFER,
    APPROVAL,
    TOP_UP_REQUEST,
    RETURN,
    DELIVERY
}