package com.company.vansales.app.datamodel.models.mastermodels

class EndOfDayRequestModel (
    val strucEodHeaders : List<StrucEodHeaders>,
    val strucEodItems : List<StrucEodItems>,
    val strucEodBatches : List<StrucEodBatches>,
    val strucEodVisitHeaders : List<StrucEodVisitHeaders>,
    val strucEodVisitItems : List<StrucEodVisitItems>,
    val strucEodTrucks : List<StrucEodTrucks>,
    val strucEodResults : List<StrucEodResults>
)
class StrucEodHeaders(
    val exInvoice : String,
    val customer : String,
    val driver : String,
    val docType : String,
    val docStatus : String,
    val erpInvoice : String,
    val visitId : String,
    val creationDate : String,
    val creationTime : String,
    val totalValue : Double,
    val paymentType : String,
    val visitItem : String?,
    val cancelInvoice : String,
    val returnReason : String,
    val totalDiscount : Double,
    val isSelleable : String,
    val approvalReq : String,
    val speratedInvoice : String,
    val freeErp : String,
    val freeExinvoice : String,
    val focAmount : Double,
    val numberSequense : String,
    val seqeuseType : String,
    val longitude : Double,
    val latitude : Double,
    val complete : String,
    val collectedAmount : Double,
    val customerizeHeader : Double,
    val customerizeField : String,
    val deliverydate : String,
    val paymentTerms : String
)
class StrucEodItems(
    val exInvoice : String,
    val itemNo : Int,
    val materialNo : String,
    val unitPrice : Double,
    val priceCurrency : String,
    val actualPrice : Double,
    val quantity : Double,
    val uom : String,
    val totalPrice : Double,
    val hhCount : Double,
    val category : String,
    val materialGrp : String,
    val grpDescription : String,
    val highLevel : String,
    val isFree : String,
    val discount : Double,
    val barcode : String,
    val focAmount : Double,
    val priceUnit : String,
    val priceAmount : Double,
    val headerExculsioncond : String,
    val refOrder : String,
    val refOrderItem : String,
    val orignalQty : Double,
    val orignalUom : String,
    val customerizeField : String
)
class StrucEodBatches(
    val exinvoice : String,
    val itemno : Int,
    val batch : String,
    val materialno : String,
    val quantity : Double,
    val uom : String,
    val iCount : Double,
    val expirydate : String,
    val iCounter : String,
    val barcode : String,
    val customerizeField : String
)
class StrucEodVisitHeaders(
    val visitlistid : String,
    val startdate : String,
    val starttime : String,
    val enddate : String,
    val endtime : String,
    val startodemeter : Double,
    val endodemeter : Double,
    val status : String,
    val driver : String,
    val visittype : String,
    val customerizeField : String
)
class StrucEodVisitItems(
    val visitlistId : String,
    val visitiItem : Int,
    val customer : String,
    val visitstatus :String,
    val visitDate : String,
    val visitTime : String,
    val odeMeterreading : Double,
    val visitType : String,
    val sequence : Int,
    val startTime : String,
    val endTime : String,
    val startLatitude : Double,
    val startLongtitude : Double,
    val endLatitude : Double,
    val endLongitude : Double,
    val failedReason : String,
    val note : String,
    val distance : Double,
    val customerizeField : String
)
class StrucEodTrucks(
    val visitList : String,
    val materialno : String,
    val batch : String,
    val openstock : Double,
    val closedstock : Double,
    val loadrequest : Double,
    val topup : Double,
    val offload : Double,
    val returnHh : Double,
    val sellable : Double,
    val uom : String,
    val customerizeField : String,
)
class StrucEodResults(
    val exDoc : String,
    val msgType : String,
    val message1 : String,
    val message2 : String
)