package com.company.vansales.app.datamodel.models.localmodels

class MaterialsTruckItem {
    var salesOrg = ""
    var distChannel = ""
    var baseUnit = ""
    var materialNo = ""
    var materialDescrption = ""
    var materialGrp = ""
    var materialType = ""
    var minShelf = 0
    var expiryDate = ""
    var salesUnit = ""
    var grpDesc = ""
    var oldMat = ""
    var totalShelf = 0
    var materialArabic = ""
    var grpArabic = ""
    var isSellable = ""
    var customizeField = ""
    var plant = ""
    var mtype = ""
    var total = 0.0
    var available = 0.0
    var selectedQuantity = 0.0
    var selectedFreeQuantity = 0.0
    var unitPrice = 0.0
    var selectedUnit = ""
    var position = 0
    var itemNo = 0
    var freePosition = 0
    var barcodeList = ArrayList<String>()
    var unitQuantityList = HashMap<String, Double>()
    var batchList = HashMap<String,HashMap<String, Double>>()
    var benefitList = ArrayList<Benefits>()
    var discountValue = 0.0
    var FOCValue = 0.0
    var isFree = ""
    var displayingValue = 0.0
    var yVatTaxes = 0.0
    var yExcTaxes = 0.0
    var totalTaxes = 0.0

    fun cloneMaterialsTruckItem(materialsTruckItem: MaterialsTruckItem) {
        this.salesOrg = materialsTruckItem.salesOrg
        this.distChannel = materialsTruckItem.distChannel
        this.baseUnit = materialsTruckItem.baseUnit
        this.materialNo = materialsTruckItem.materialNo
        this.materialDescrption = materialsTruckItem.materialDescrption
        this.materialGrp = materialsTruckItem.materialGrp
        this.materialType = materialsTruckItem.materialType
        this.minShelf = materialsTruckItem.minShelf
        this.expiryDate = materialsTruckItem.expiryDate
        this.salesUnit = materialsTruckItem.salesUnit
        this.grpDesc = materialsTruckItem.grpDesc
        this.oldMat = materialsTruckItem.oldMat
        this.totalShelf = materialsTruckItem.totalShelf
        this.materialArabic = materialsTruckItem.materialArabic
        this.grpArabic = materialsTruckItem.grpArabic
        this.isSellable = materialsTruckItem.isSellable
        this.customizeField = materialsTruckItem.customizeField
        this.plant = materialsTruckItem.plant
        this.mtype = materialsTruckItem.mtype
        this.total = materialsTruckItem.total
        this.available = materialsTruckItem.available
        this.selectedQuantity = materialsTruckItem.selectedQuantity
        this.unitPrice = materialsTruckItem.unitPrice
        this.selectedUnit = materialsTruckItem.selectedUnit
        this.barcodeList = materialsTruckItem.barcodeList
        this.unitQuantityList = HashMap(materialsTruckItem.unitQuantityList)
        this.unitQuantityList[selectedUnit] = this.selectedQuantity
        this.batchList = HashMap(materialsTruckItem.batchList)
        this.position = materialsTruckItem.position
        this.isFree = materialsTruckItem.isFree
        this.freePosition = materialsTruckItem.freePosition
        this.displayingValue = materialsTruckItem.displayingValue
        this.yVatTaxes = materialsTruckItem.yVatTaxes
        this.yExcTaxes = materialsTruckItem.yExcTaxes
        this.totalTaxes = materialsTruckItem.totalTaxes
    }
    fun cloneMaterialsTruckItem(materialsTruckItem: MaterialsTruckItem , selectedQuantity : Double) {
        this.salesOrg = materialsTruckItem.salesOrg
        this.distChannel = materialsTruckItem.distChannel
        this.baseUnit = materialsTruckItem.baseUnit
        this.materialNo = materialsTruckItem.materialNo
        this.materialDescrption = materialsTruckItem.materialDescrption
        this.materialGrp = materialsTruckItem.materialGrp
        this.materialType = materialsTruckItem.materialType
        this.minShelf = materialsTruckItem.minShelf
        this.expiryDate = materialsTruckItem.expiryDate
        this.salesUnit = materialsTruckItem.salesUnit
        this.grpDesc = materialsTruckItem.grpDesc
        this.oldMat = materialsTruckItem.oldMat
        this.totalShelf = materialsTruckItem.totalShelf
        this.materialArabic = materialsTruckItem.materialArabic
        this.grpArabic = materialsTruckItem.grpArabic
        this.isSellable = materialsTruckItem.isSellable
        this.customizeField = materialsTruckItem.customizeField
        this.plant = materialsTruckItem.plant
        this.mtype = materialsTruckItem.mtype
        this.total = materialsTruckItem.total
        this.available = materialsTruckItem.available
        this.selectedQuantity = materialsTruckItem.selectedQuantity
        this.unitPrice = materialsTruckItem.unitPrice
        this.selectedUnit = materialsTruckItem.selectedUnit
        this.barcodeList = materialsTruckItem.barcodeList
        this.unitQuantityList = HashMap(materialsTruckItem.unitQuantityList)
//        this.unitQuantityList[selectedUnit] = selectedQuantity
        this.batchList = HashMap(materialsTruckItem.batchList)
        this.position = materialsTruckItem.position
        this.isFree = materialsTruckItem.isFree
        this.freePosition = materialsTruckItem.freePosition
        this.displayingValue = materialsTruckItem.displayingValue
        this.yVatTaxes = materialsTruckItem.yVatTaxes
        this.yExcTaxes = materialsTruckItem.yExcTaxes
        this.totalTaxes = materialsTruckItem.totalTaxes
    }
}